name = "hitmap"
type = "javascript"
compatibility_date = "2022-09-04"

[[kv_namespaces]]
binding = "hitmaps"
id = "ba1e0740a8f64f60be6578643d1d013c"
preview_id = "d5e287a6482542208ad85ca6718c0cda"

[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
